<?php

/**
 * Description of ServiciosGarantiasController
 *
 * AUTOGENERATED

 * @author Sergio Pérez <sergio.perez@albatronic.com>
 * @copyright Informática ALBATRONIC
 * @date 25-Jul-2014
 *
 */
class ServiciosGarantiaController extends ControllerProject {

    protected $controller = "ServiciosGarantia";

}