<?php

/**
 * Description of AvisoCookiesController
 *
 * AUTOGENERATED

 * @author Sergio Pérez <sergio.perez@albatronic.com>
 * @copyright Informática ALBATRONIC
 * @date 28-Mar-2015
 *
 */
class AvisoCookiesController extends ControllerProject {

    protected $controller = "AvisoCookies";

}