<?php

/**
 * Description of PedidossController
 *
 * AUTOGENERATED

 * @author Sergio Pérez <sergio.perez@albatronic.com>
 * @copyright Informática ALBATRONIC
 * @date 25-Jul-2014
 *
 */
class PedidosController extends ControllerProject {

    protected $controller = "Pedidos";

}