<?php

/**
 * Description of CondicionesVentaController
 *
 * AUTOGENERATED

 * @author Sergio Pérez <sergio.perez@albatronic.com>
 * @copyright Informática ALBATRONIC
 * @date 28-Mar-2015
 *
 */
class CondicionesVentaController extends ControllerProject {

    protected $controller = "CondicionesVenta";

}