<?php

/**
 * Description of QuienesSomossController
 *
 * AUTOGENERATED

 * @author Sergio Pérez <sergio.perez@albatronic.com>
 * @copyright Informática ALBATRONIC
 * @date 25-Jul-2014
 *
 */
class QuienesSomosController extends ControllerProject {

    protected $controller = "QuienesSomos";

}